package com.soda.rules

import com.soda.helper.SodaUI

rule "init"
when
	sodaUI: SodaUI()
then
    sodaUI.setQuestionString("Are you in mexico?");
    // update(sodaUI);
    System.out.println("SGAGYUSGA");
end

rule "nas"
when
then
	System.out.println("asihaio");
end

rule "Question 1: Are you mexican?"
when
    sodaUI : SodaUI(sodaUI.getQuestionString() == "Are you in mexico?")
then
    System.out.println("He is in Mexico."); 
    sodaUI.setQuestionString("Are you in Poland?");
    System.out.println(sodaUI.getSelectedAnswer());
    System.out.println(sodaUI.getQuestionString());
    update(sodaUI);
end

rule "Question 2: Are you polish?"
when
    sodaUI : SodaUI(sodaUI.getQuestionString() == "Are you in Poland?",
    sodaUI.getSelectedAnswer() == "Yes")
then
    System.out.println("He is in Poland."); 
    
    sodaUI.setQuestionString("Are you French?");
    update(sodaUI);
end

rule "Question 3: Are you French?"
when
    sodaUI : SodaUI(sodaUI.getQuestionString() == "Are you French?")
then
    System.out.println("He is french."); 
    sodaUI.setQuestionString("Are you stupid?");
    update(sodaUI);
end